# Generated by Django 5.0.3 on 2026-06-15 11:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color_code', models.CharField(max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'lines',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('has_kiosk', models.BooleanField(default=False)),
                ('gtfs_stop_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'stations',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=50, unique=True)),
                ('fleet_id', models.CharField(max_length=50, unique=True)),
                ('driver_id', models.UUIDField(blank=True, null=True)),
                ('capacity', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='ImportedStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('formatted_address', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('OSM', 'OpenStreetMap'), ('GOOGLE', 'Google Places'), ('GTFS', 'GTFS'), ('MANUAL', 'Manual')], default='OSM', max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('type', models.CharField(choices=[('BUS', 'Bus'), ('METRO', 'Metro'), ('TRAIN', 'Train'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_sources', to='transit_tracking.station')),
            ],
            options={
                'verbose_name': 'Imported Station',
                'verbose_name_plural': 'Imported Stations',
                'db_table': 'imported_stations',
            },
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('path_coordinates', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gtfs_route_id', models.CharField(blank=True, max_length=100, null=True)),
                ('end_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trajets_ending_here', to='transit_tracking.station')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit_tracking.line')),
                ('start_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trajets_starting_here', to='transit_tracking.station')),
            ],
            options={
                'db_table': 'trajets',
            },
        ),
        migrations.CreateModel(
            name='ImportedRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('OSM', 'OpenStreetMap'), ('GOOGLE', 'Google Places'), ('GTFS', 'GTFS'), ('MANUAL', 'Manual')], default='GTFS', max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('line_name', models.CharField(blank=True, max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_trajet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_sources', to='transit_tracking.trajet')),
            ],
            options={
                'verbose_name': 'Imported Route',
                'verbose_name_plural': 'Imported Routes',
                'db_table': 'imported_routes',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_id', models.UUIDField()),
                ('last_latitude', models.FloatField(blank=True, null=True)),
                ('last_longitude', models.FloatField(blank=True, null=True)),
                ('last_gps_update_time', models.DateTimeField(blank=True, null=True)),
                ('scheduled_start', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='SCHEDULED', max_length=50)),
                ('gtfs_trip_id', models.CharField(blank=True, max_length=100, null=True)),
                ('current_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_currently_here', to='transit_tracking.station')),
                ('destination_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_destined_here', to='transit_tracking.station')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='transit_tracking.trajet')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='transit_tracking.vehicle')),
            ],
            options={
                'db_table': 'trips',
            },
        ),
        migrations.CreateModel(
            name='GPSLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_id', models.UUIDField()),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('speed_kmh', models.DecimalField(decimal_places=2, max_digits=5)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='transit_tracking.trip')),
            ],
            options={
                'db_table': 'gps_logs',
            },
        ),
        migrations.CreateModel(
            name='DriverIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_id', models.UUIDField()),
                ('type', models.CharField(choices=[('DELAY', 'Delay'), ('BREAKDOWN', 'Breakdown'), ('ACCIDENT', 'Accident'), ('SECURITY', 'Security'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField()),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transit_tracking.trip')),
            ],
            options={
                'db_table': 'driver_incidents',
            },
        ),
        migrations.CreateModel(
            name='DriverSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_id', models.UUIDField()),
                ('current_order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('ARRIVED_AT_STATION', 'Arrived at Station'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('arrival_station', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sessions_arrived', to='transit_tracking.station')),
                ('current_station', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sessions_current', to='transit_tracking.station')),
                ('departure_station', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sessions_departed', to='transit_tracking.station')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='transit_tracking.trajet')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='transit_tracking.vehicle')),
            ],
            options={
                'db_table': 'driver_sessions',
            },
        ),
        migrations.CreateModel(
            name='ImportedRouteStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.PositiveIntegerField()),
                ('time_to_next_station', models.PositiveIntegerField(default=5, help_text='Minutes from this station to the next')),
                ('imported_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imported_stations', to='transit_tracking.importedroute')),
                ('imported_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit_tracking.importedstation')),
            ],
            options={
                'db_table': 'imported_route_stations',
                'ordering': ['order_number'],
                'unique_together': {('imported_route', 'order_number')},
            },
        ),
        migrations.CreateModel(
            name='TrajetStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.PositiveIntegerField()),
                ('time_to_next_station', models.PositiveIntegerField(default=5, help_text='Minutes from this station to the next')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit_tracking.station')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajet_stations', to='transit_tracking.trajet')),
            ],
            options={
                'db_table': 'trajet_stations',
                'ordering': ['order_number'],
                'unique_together': {('trajet', 'order_number'), ('trajet', 'station')},
            },
        ),
    ]
