# Generated by Django 5.0.3 on 2026-06-14 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_validation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.CharField(choices=[('DAILY', 'Quotidien'), ('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuel')], max_length=10)),
                ('duration_days', models.IntegerField(help_text='Nombre de jours de validité')),
                ('price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('zone_validity', models.CharField(default='ALL', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscription_types',
            },
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('STANDARD', 'Standard'), ('STUDENT', 'Étudiant'), ('PMR', 'Personne à mobilité réduite'), ('CHILD', 'Enfant'), ('SENIOR', 'Senior')], default='STANDARD', max_length=20)),
                ('zone_from', models.CharField(max_length=50)),
                ('zone_to', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fares',
                'unique_together': {('category', 'zone_from', 'zone_to')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_type', models.CharField(choices=[('TICKET', 'Ticket'), ('SUBSCRIPTION', 'Abonnement'), ('RECHARGE', 'Recharge')], max_length=20)),
                ('reference_id', models.UUIDField(help_text='ID du ticket/abonnement/recharge associé')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('pdf_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='MultiPassengerTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passengers', models.JSONField(help_text="Liste des passagers: [{'name': '...', 'cin': '...'}]")),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='purchased_tickets', to=settings.AUTH_USER_MODEL)),
                ('tickets', models.ManyToManyField(related_name='multi_passenger_group', to='ticketing_validation.ticket')),
            ],
            options={
                'db_table': 'multi_passenger_tickets',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('price_paid', models.DecimalField(decimal_places=3, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ticketing_validation.subscriptiontype')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
    ]
