# Generated by Django 5.0.3 on 2026-06-15 11:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transit_tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('DELAY', 'Retard'), ('CANCELLATION', 'Annulation'), ('IMMINENT_ARRIVAL', 'Arrivée imminente'), ('TICKET_EXPIRING', 'Expiration ticket'), ('BROADCAST', 'Diffusion générale'), ('INCIDENT', 'Incident signalé'), ('FRAUD_ALERT', 'Alerte fraude')], max_length=30, unique=True)),
                ('title_template', models.CharField(max_length=200)),
                ('body_template', models.TextField()),
                ('push_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('email_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_type', models.CharField(choices=[('TECHNICAL', 'Panne technique'), ('ACCIDENT', 'Accident'), ('SECURITY', 'Incident sécurité'), ('DELAY', 'Retard majeur'), ('OTHER', 'Autre')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], default='MEDIUM', max_length=10)),
                ('description', models.TextField()),
                ('location_lat', models.FloatField(blank=True, null=True)),
                ('location_lng', models.FloatField(blank=True, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='incident_reports', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transit_tracking.trip')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transit_tracking.vehicle')),
            ],
            options={
                'db_table': 'incident_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('DELAY', 'Retard'), ('CANCELLATION', 'Annulation'), ('IMMINENT_ARRIVAL', 'Arrivée imminente'), ('TICKET_EXPIRING', 'Expiration ticket'), ('BROADCAST', 'Diffusion générale'), ('INCIDENT', 'Incident signalé'), ('FRAUD_ALERT', 'Alerte fraude')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_via_push', models.BooleanField(default=False)),
                ('sent_via_sms', models.BooleanField(default=False)),
                ('sent_via_email', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_2d3764_idx'), models.Index(fields=['-created_at'], name='notificatio_created_8fa075_idx')],
            },
        ),
    ]
