# Generated by Django 5.0.3 on 2026-05-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PASSENGER', 'Passenger'), ('DRIVER', 'Driver'), ('CONTROLLER', 'Controller'), ('ADMIN', 'Admin')], default='PASSENGER', max_length=20),
        ),
    ]
