# Generated by Django 5.0.3 on 2026-05-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_identity', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PASSENGER', 'Passenger'), ('DRIVER', 'Driver'), ('CONTROLLER', 'Controller'), ('ADMIN', 'Admin'), ('SUPER_ADMIN', 'Super Admin')], default='PASSENGER', max_length=20),
        ),
    ]
